# Generated by Django 4.0.8 on 2022-10-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_posted']},
        ),
        migrations.DeleteModel(
            name='Article_Images',
        ),
    ]
