# Generated by Django 4.0.8 on 2022-10-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.tag'),
        ),
        migrations.AlterField(
            model_name='article_images',
            name='image',
            field=models.FileField(upload_to='static/images/'),
        ),
    ]
