# Generated by Django 4.0.8 on 2022-10-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
