# Generated by Django 4.0.8 on 2022-11-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_note_options_note_note_posted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-note_created']},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_posted',
            new_name='note_created',
        ),
        migrations.RemoveField(
            model_name='note',
            name='article',
        ),
    ]
